services:
  agent-zero-cuda:
    container_name: agent-zero-cuda
    image: ilbaks/ilbaks/agent-zero-run:hacking
    volumes:
      - ./agent-zero:/a0
      - ./agent-zero/work_dir:/root
    ports:
      - "52022:22"
      - "52080:80"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu] 